#!/bin/bash
set -e
BASE="http://127.0.0.1:9000"
OUTDIR="/splunk-data/v1/Work_RAG-Server-Setup/logs"
mkdir -p "$OUTDIR"
TS=$(date +%Y%m%d_%H%M%S)
LOG="$OUTDIR/manager_test_$TS.json"
echo "=== Manager test $TS ===" | tee "$LOG"
echo "--- GET /health ---" | tee -a "$LOG"
curl -s "$BASE/health" | python3 -m json.tool | tee -a "$LOG"
echo "--- GET /v1/models ---" | tee -a "$LOG"
curl -s "$BASE/v1/models" | python3 -m json.tool | tee -a "$LOG"
echo "--- GET /v1/models/gemma-4-31b ---" | tee -a "$LOG"
curl -s "$BASE/v1/models/gemma-4-31b" | python3 -m json.tool | tee -a "$LOG"
echo "--- POST /v1/chat/completions gemma-4-31b ---" | tee -a "$LOG"
curl -s "$BASE/v1/chat/completions" -H "Content-Type: application/json" -d '{"model":"gemma-4-31b","messages":[{"role":"user","content":"say hello in one word"}],"max_tokens":10}' | python3 -m json.tool | tee -a "$LOG"
echo "--- POST /v1/chat/completions qwen2.5-7b ---" | tee -a "$LOG"
curl -s "$BASE/v1/chat/completions" -H "Content-Type: application/json" -d '{"model":"qwen2.5-7b","messages":[{"role":"user","content":"salam be farsi yek kalame begu"}],"max_tokens":10}' | python3 -m json.tool | tee -a "$LOG"
echo "--- POST /v1/completions (legacy) ---" | tee -a "$LOG"
curl -s "$BASE/v1/completions" -H "Content-Type: application/json" -d '{"model":"gemma-4-31b","prompt":"Hello world","max_tokens":10}' 2>&1 | head -c 1000 | tee -a "$LOG" || echo "legacy endpoint may not exist" | tee -a "$LOG"
echo "--- POST /v1/chat/completions with session_id ---" | tee -a "$LOG"
SID="test-$(date +%s)"
curl -s "$BASE/v1/chat/completions" -H "Content-Type: application/json" -d "{\"model\":\"gemma-4-31b\",\"messages\":[{\"role\":\"user\",\"content\":\"my name is Ali\"}],\"max_tokens\":20, \"session_id\":\"$SID\"}" | python3 -m json.tool | tee -a "$LOG"
curl -s "$BASE/v1/chat/completions" -H "Content-Type: application/json" -d "{\"model\":\"gemma-4-31b\",\"messages\":[{\"role\":\"user\",\"content\":\"what is my name?\"}],\"max_tokens\":20, \"session_id\":\"$SID\"}" | python3 -m json.tool | tee -a "$LOG"
echo "--- GET /admin/status (if exists) ---" | tee -a "$LOG"
curl -s "$BASE/admin/status" 2>&1 | python3 -m json.tool | tee -a "$LOG" || echo "no admin/status" | tee -a "$LOG"
echo "--- GET embeddings health ---" | tee -a "$LOG"
for p in 8001 8002 8003; do echo "port $p:"; curl -s http://127.0.0.1:$p/health | cat; echo; done | tee -a "$LOG"
echo "=== Done log $LOG ==="
cat "$LOG"
